### ISSUE TITLE
Wallet has been recovered, SINOVATE Node has not updated mined SIN

### ISSUE THREAD

**Issue by jpower1196** [SINOVATEblockchain/SINWebTool#25]
I have recovered my wallet from when my SIN-CORE wallet, but the last time I received any SIN was on July 9th 2021. Usually I receive 560 SIN every 1-2 days. Is this due to when I copied my wallet data, or is there something that I did incorrectly? Sorry for the inconvenience, thank you for any information that anyone can help me with.

**Comment by hardwarewise** [comment]
Your reward period seems normal for now. 
And the issue has nothing to do with this repo.
Thank you for your attention.
